main: com.aidn5.mcqa.MCQA
name: MCQA
version: 0.1
author: aidn5
description: add commands to add/view written guides/tutorials/tips for players
website: github.com/aidn3
api-version: 1.14
commands:
   qa:
      description: search for contents/guides/tutorials
      usage: /qa <search>
   qaget:
      description: get and view Contents/guides/tutorials
      usage: /<command> <content id>
   qaadd:
      description: open GUI to add new contents
      usage: /<command> <category> <question>
   qadel:
      description: remove a content
      usage: /<command> <content id>
   qacopy:
      description: copy content to the held book
      usage: /<command> <content id>
   qaprove:
      description: get all unproved contents to prove/remove
permissions:
   mcqa.viewContents:
      description: Allow to view the contents
      default: true
   mcqa.getAllContents:
      description: Allow to view all contents (approved and not approved)
      children:
         mcqa.viewContents: true
   mcqa.approveContents:
      description: Allow to approve contents to be seen by the public
      children:
         mcqa.viewContents: true
         mcqa.getAllContents: true
   mcqa.addContents:
      description: Allow to add new contents
      children:
         mcqa.viewContents: true
   mcqa.removeContents:
      description: Allow to remove contents
   mcqa.copyContents:
      description: Allow to copy contents to book
      children:
         mcqa.viewContents: true
      default: true
   mcqa.copyContents.bypassRequireBook:
      description: By pass the error when not holding a book and want a copy
      children:
         mcqa.copyContents: true
   mcqa.editContents:
      description: Allow to edit/add more contents
      children:
         mcqa.viewContents: true
         mcqa.addContents: true
         mcqa.copyContents: true
   mcqa.*:
      description: Wildcard permission
      default: op
      children:
         mcqa.viewContents: true
         mcqa.getAllContents: true
         mcqa.approveContents: true
         mcqa.addContents: true
         mcqa.editContents: true
         mcqa.copyContents: true
         mcqa.copyContents.bypassRequireBook: true